language: python
services:
  - docker

before_install:
  - docker build -t ldap/test tests/ldap
  - docker run -d -p 127.0.0.1:389:389 ldap/test
  - docker ps -a

cache: pip
dist: focal
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements/dev.txt
# command to run tests
before_script:
  - cd idmdemo
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
